name: forkfable
description: "Social Rating Food App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed: ^2.5.8
  json_annotation: ^4.9.0
  envied: ^1.1.1
  auto_route: ^9.3.0+1
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0
  custom_lint: ^0.7.3
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.15
  riverpod_lint: ^2.6.4
  json_serializable: ^6.9.4
  envied_generator: ^1.1.1
  auto_route_generator: ^9.3.1
  slang_build_runner: ^4.4.2

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
